# Generated by Django 3.2.13 on 2022-10-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=10)),
                ('cost', models.IntegerField(max_length=10)),
                ('weight', models.IntegerField(max_length=10)),
                ('image', models.CharField(max_length=30)),
            ],
        ),
    ]
