# Generated by Django 3.2.13 on 2023-09-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0002_alter_stuff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
