# Generated by Django 3.2.13 on 2023-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0004_auto_20230930_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=models.CharField(max_length=256),
        ),
    ]
